services:
  ray-head:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: ${RAY_IMAGE}
    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
    env_file:
      - ../.env
    environment:
      - RAY_USE_MULTIPROCESSING_CPU_COUNT=1
      - RAY_DISABLE_DOCKER_CPU_WARNING=1
    command: >
      bash -c "uv run ray start
      --head
      --num-cpus 1
      --include-dashboard false
      --block"
    shm_size: 2g
    healthcheck:
      test: ["CMD", "uv", "run", "ray", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net

  ray-worker:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    image: ${RAY_IMAGE}
    depends_on:
      ray-head:
        condition: service_healthy
    environment:
      - RAY_GCS_RPC_TIMEOUT_MS=30000
    command: >
      bash -c "uv run ray start
      --address=ray-head:6379
      --num-cpus=${NUM_CPU_WORKER}
      --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}
      resources:
        limits:
          cpus: ${NUM_CPU_WORKER}
          memory: '2g'
    networks:
      - ray_net

networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16
